apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic-rest
  ports:
    - protocol: TCP
      port: 9966
      targetPort: 9966
